### ISSUE TITLE
{"error_code":"403003","message":"Api Key is invalid"}

### ISSUE THREAD

**Issue by gradus0** [AdobeDocs/lightroom-api-docs#17]
Hi, i use php and cron, send to https://image.adobe.io/lrService/presets
Content-Type: application/json
authorization: Bearer {token}
x-api-key: {api_key}

key and token is true, but server return 
{"error_code":"403003","message":"Api Key is invalid"}

i check api this -> https://lr.adobe.io/v2/health
return ok: {"version":{version}}

What is problem, server adobe it's work ?

**Comment by shayanc1985** [comment]
Hi @gradus0 
The health API that you are checking is for a different Lr service. To be able to use the /presets API you would need to add `Adobe Photoshop APIs (Trial)` into your integration under the APIs tab.
Also please note that you will only be allowed to create `Service Account (JWT)` integration and not the OAuth authentication. Please let me know if you have any more questions!

**Comment by gradus0** [comment]
> Hi @gradus0
> The health API that you are checking is for a different Lr service. To be able to use the /presets API you would need to add `Adobe Photoshop APIs (Trial)` into your integration under the APIs tab.
> Also please note that you will only be allowed to create `Service Account (JWT)` integration and not the OAuth authentication. Please let me know if you have any more questions!
Thanks it's work!)
